apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: mongodb-persistent
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: "mongodb-internal"
    labels:
      name: "mongodb"
    annotations:
      service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  spec:
    clusterIP: None
    ports:
      - name: mongodb
        port: 27017
    selector:
      name: "mongodb"
- kind: Service
  apiVersion: v1
  metadata:
    name: "mongodb"
    labels:
      name: "mongodb"
  spec:
    ports:
      - name: mongodb
        port: 27017
    selector:
      name: "mongodb"
- kind: StatefulSet
  apiVersion: apps/v1
  metadata:
    name: "mongodb"
  spec:
    serviceName: "mongodb-internal"
    replicas: 3
    selector:
      matchLabels:
        name: mongodb
    template:
      metadata:
        labels:
          name: "mongodb"
      spec:
        containers:
          - name: mongo-container
            image: "registry.access.redhat.com/rhscl/mongodb-34-rhel7:latest"
            ports:
              - containerPort: 27017
            args:
              - "run-mongod-replication"
            volumeMounts:
              - name: mongo-data
                mountPath: "/var/lib/mongodb/data"
            env:
              - name: MONGODB_DATABASE
                value: ${MONGODB_DATABASE}
              - name: MONGODB_USER
                value: ${MONGODB_USER}
              - name: MONGODB_PASSWORD
                value: ${MONGODB_PASSWORD}
              - name: MONGODB_ADMIN_PASSWORD
                value: ${MONGODB_ADMIN_PASSWORD}
              - name: MONGODB_REPLICA_NAME
                value: "rs0"
              - name: MONGODB_KEYFILE_VALUE
                value: "12345678901234567890"
              - name: MONGODB_SERVICE_NAME
                value: ${MONGODB_SERVICE_NAME}
            readinessProbe:
              exec:
                command:
                  - stat
                  - /tmp/initialized
    volumeClaimTemplates:
      - metadata:
          name: mongo-data
          labels:
            name: "mongodb"
        spec:
          accessModes: [ ReadWriteOnce ]
          resources:
            requests:
              storage: ${MONGODB_VOLUME}

parameters:
  - displayName: Mongo database name
    name: MONGODB_DATABASE
    required: true
    value: mongodb
  - displayName: Mongo username
    name: MONGODB_USERNAME
    required: true
    value: mongodb_user
  - displayName: Mongo password
    name: MONGODB_PASSWORD
    required: true
    value: mongodb_password
  - displayName: Mongo admin password
    name: MONGODB_ADMIN_PASSWORD
    required: true
    value: mongodb_admin_password
  - displayName: Mongo volume size
    name: MONGODB_VOLUME
    required: true
    value: 4Gi
  - displayName: Mongo service name
    name: MONGODB_SERVICE_NAME
    required: true
    value: mongodb-internal